# Generated by Django 4.1.5 on 2023-01-31 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flightseats', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserBooking',
        ),
        migrations.AddField(
            model_name='book',
            name='reserved_by',
            field=models.CharField(default='none', max_length=30),
        ),
    ]
