# Generated by Django 4.1.4 on 2023-01-10 00:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flightseats', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='flight',
            name='destination',
        ),
        migrations.AddField(
            model_name='flight',
            name='airline',
            field=models.CharField(default='Airline', max_length=250),
        ),
        migrations.AddField(
            model_name='flight',
            name='day',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='flight',
            name='departure',
            field=models.CharField(default='Time', max_length=250),
        ),
        migrations.AddField(
            model_name='flight',
            name='dest_airport',
            field=models.CharField(default='destination', max_length=250),
        ),
        migrations.AddField(
            model_name='flight',
            name='flight_number',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='flight',
            name='month',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='flight',
            name='origin_airport',
            field=models.CharField(default='Airport', max_length=250),
        ),
        migrations.AddField(
            model_name='flight',
            name='year',
            field=models.IntegerField(default=0),
        ),
    ]
