# Generated by Django 4.1.5 on 2023-01-25 21:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flightseats', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserBooking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('seat_choice', models.CharField(default='none', max_length=30, unique=True)),
                ('reserved_by', models.CharField(default='none', max_length=30, unique=True)),
            ],
        ),
    ]
