# Generated by Django 4.1.5 on 2023-01-31 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flightseats', '0002_delete_userbooking_book_reserved_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='booking_time',
            field=models.CharField(default='none', max_length=30),
        ),
    ]
