# Generated by Django 4.1.4 on 2023-01-10 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flightseats', '0002_remove_flight_destination_flight_airline_flight_day_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('airline', models.CharField(default='Airline', max_length=250)),
            ],
        ),
        migrations.AddField(
            model_name='seats',
            name='column',
            field=models.CharField(default='A', max_length=250),
        ),
        migrations.AddField(
            model_name='seats',
            name='row',
            field=models.IntegerField(default=0),
        ),
    ]
