# Generated by Django 4.1.5 on 2023-01-25 21:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flightseats', '0002_userbooking'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userbooking',
            name='reserved_by',
            field=models.CharField(default='none', max_length=30),
        ),
    ]
