# Generated by Django 4.1.4 on 2023-01-11 19:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flightseats', '0003_book_seats_column_seats_row'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='empty', max_length=250)),
                ('user_name', models.CharField(default='empty', max_length=250)),
                ('password', models.CharField(default='empty', max_length=250)),
            ],
        ),
    ]
