# Generated by Django 4.1.4 on 2023-01-11 19:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flightseats', '0004_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='seats',
            old_name='column',
            new_name='column_a',
        ),
        migrations.RemoveField(
            model_name='seats',
            name='row',
        ),
        migrations.AddField(
            model_name='seats',
            name='column_b',
            field=models.CharField(default='A', max_length=250),
        ),
        migrations.AddField(
            model_name='seats',
            name='column_c',
            field=models.CharField(default='A', max_length=250),
        ),
        migrations.AddField(
            model_name='seats',
            name='column_d',
            field=models.CharField(default='A', max_length=250),
        ),
        migrations.AddField(
            model_name='seats',
            name='column_e',
            field=models.CharField(default='A', max_length=250),
        ),
        migrations.AddField(
            model_name='seats',
            name='column_f',
            field=models.CharField(default='A', max_length=250),
        ),
        migrations.AddField(
            model_name='seats',
            name='column_g',
            field=models.CharField(default='A', max_length=250),
        ),
        migrations.AddField(
            model_name='seats',
            name='column_h',
            field=models.CharField(default='A', max_length=250),
        ),
        migrations.AddField(
            model_name='seats',
            name='column_i',
            field=models.CharField(default='A', max_length=250),
        ),
    ]
