# Generated by Django 4.1.4 on 2023-01-11 23:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flightseats', '0005_rename_column_seats_column_a_remove_seats_row_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Seats2',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
    ]
