# Generated by Django 4.1.4 on 2023-01-11 23:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('flightseats', '0006_seats2'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='seats',
            name='booked',
        ),
    ]
