# Generated by Django 4.1.5 on 2023-01-13 23:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('flightseats', '0007_remove_seats_booked'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='seats',
            name='column_h',
        ),
        migrations.RemoveField(
            model_name='seats',
            name='column_i',
        ),
    ]
