# Generated by Django 4.1.4 on 2023-01-16 00:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flightseats', '0008_remove_seats_column_h_remove_seats_column_i'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='airline',
        ),
        migrations.AddField(
            model_name='book',
            name='seat_choice',
            field=models.CharField(default='none', max_length=30, unique=True),
        ),
    ]
