# Generated by Django 4.1.5 on 2023-01-17 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flightseats', '0010_alter_book_seat_choice'),
    ]

    operations = [
        migrations.AddField(
            model_name='seats2',
            name='rows',
            field=models.CharField(default='A', max_length=250),
        ),
    ]
