# Generated by Django 4.1.5 on 2023-01-21 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flightseats', '0011_seats2_rows'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='seat_choice',
            field=models.CharField(default='none', max_length=30, unique=True),
        ),
    ]
