# Generated by Django 4.1.5 on 2023-01-24 15:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('flightseats', '0012_alter_book_seat_choice'),
        ('flightseats', '0012_alter_book_seat_choice_alter_user_name_and_more'),
    ]

    operations = [
    ]
