# Generated by Django 4.1.5 on 2023-01-24 15:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('flightseats', '0013_merge_20230124_1626'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Seats2',
        ),
    ]
